kind: pipeline
type: docker
name: telegram-bot

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world!
    when:
      event:
        - push
        - rollback
      branch:
        - master