telegram:
  bot:
    chat-id: ${BOT_CHAT_ID}
    token: ${BOT_TOKEN}
    bot-name: ${BOT_USERNAME}
    meme-api-host-url: ${MEME_API_HOST_URL}
    persistence: ${PERSISTENCE_MODE:redis}
redis:
  uri: ${REDIS_HOST}
